// Schemas
export {
  captureSchema,
  captureTypeEnum,
  captureStatusEnum,
  captureSourceTypeEnum,
  extractionTypeEnum,
  groundingSpanSchema,
  captureExtractionSchema,
  fewShotExampleSchema,
  correctionStatsSchema,
  reassignCaptureSchema,
  deviceClassificationSchema,
  createCaptureSchema,
  updateCaptureSchema,
  captureIdSchema,
  listCapturesQuerySchema,
} from "./schemas/capture.js";

export {
  projectSchema,
  projectHostEnum,
  projectSlugSchema,
  projectListQuerySchema,
} from "./schemas/project.js";

export {
  apiErrorSchema,
  healthResponseSchema,
  searchQuerySchema,
  searchResultSchema,
  searchResponseSchema,
} from "./schemas/api.js";

export {
  machineSchema,
  createMachineSchema,
  machineIdSchema,
  machineOsEnum,
  machineArchEnum,
  portProtocolEnum,
  portAllocationStatusEnum,
  portLiveStatusEnum,
  portAllocationSchema,
  createPortAllocationSchema,
  updatePortAllocationSchema,
  listPortsQuerySchema,
  portAllocationIdSchema,
  portScanEntrySchema,
  portScanIngestSchema,
  autoAllocateSchema,
  portRangeSchema,
  portMapEntrySchema,
} from "./schemas/port.js";

export {
  healthCheckTypeEnum,
  healthSeverityEnum,
  riskLevelEnum,
  copyHostEnum,
  healthFindingSchema,
  healthFindingInputSchema,
  projectCopySchema,
  healthFindingResponseSchema,
  healthCheckResponseSchema,
  healthCheckDetailResponseSchema,
  risksResponseSchema,
  copyResponseSchema,
  copiesListResponseSchema,
  copiesDetailResponseSchema,
} from "./schemas/health.js";

export {
  sessionSourceEnum,
  sessionStatusEnum,
  modelTierEnum,
  createSessionSchema,
  heartbeatSchema,
  stopSessionSchema,
  sessionSchema,
  sessionResponseSchema,
  listSessionsQuerySchema,
} from "./schemas/session.js";

export {
  burnRateEnum,
  weeklyBudgetSchema,
  routingSuggestionSchema,
  budgetResponseSchema,
} from "./schemas/budget.js";

export {
  lmStudioHealthEnum,
  lmStudioStatusSchema,
  modelsResponseSchema,
} from "./schemas/models.js";

export {
  discoveryHostEnum,
  discoveryStatusEnum,
  discoverySchema,
  createDiscoverySchema,
  updateDiscoveryStatusSchema,
  listDiscoveriesQuerySchema,
  discoveryIdSchema,
} from "./schemas/discovery.js";

export {
  starIntentEnum,
  starSchema,
  createStarSchema,
  updateStarIntentSchema,
  listStarsQuerySchema,
  starIdSchema,
} from "./schemas/star.js";

export {
  knowledgeResponseSchema,
  knowledgeListResponseSchema,
} from "./schemas/knowledge.js";

export {
  recordVisitSchema,
  getVisitQuerySchema,
  visitResponseSchema,
} from "./schemas/visit.js";

export {
  insightTypeEnum,
  insightSchema,
} from "./schemas/insight.js";

export {
  solutionProblemTypeEnum,
  solutionSeverityEnum,
  solutionStatusEnum,
  solutionReferenceTypeEnum,
  solutionSchema,
  createSolutionSchema,
  updateSolutionStatusSchema,
  updateSolutionMetadataSchema,
  listSolutionsQuerySchema,
  solutionReferenceSchema,
  compoundScoreSchema,
} from "./schemas/solution.js";

// Types
export type {
  Capture,
  CreateCapture,
  UpdateCapture,
  ListCapturesQuery,
  Project,
  ProjectListQuery,
  ApiError,
  HealthResponse,
  SearchQuery,
  SearchResult,
  SearchResponse,
  Machine,
  CreateMachine,
  PortAllocation,
  CreatePortAllocation,
  UpdatePortAllocation,
  ListPortsQuery,
  PortScanEntry,
  PortScanIngest,
  AutoAllocateRequest,
  PortRange,
  PortMapEntry,
  HealthCheckType,
  HealthSeverity,
  RiskLevel,
  CopyHost,
  HealthFinding,
  HealthFindingInput,
  ProjectCopy,
  HealthFindingResponse,
  HealthCheckResponse,
  RisksResponse,
  CopyResponse,
  SessionSource,
  SessionStatus,
  ModelTier,
  CreateSession,
  Heartbeat,
  StopSession,
  Session,
  SessionResponse,
  ListSessionsQuery,
  BurnRate,
  WeeklyBudget,
  RoutingSuggestion,
  BudgetResponse,
  LmStudioHealth,
  LmStudioStatus,
  ModelsResponse,
  DiscoveryHost,
  DiscoveryStatus,
  Discovery,
  CreateDiscovery,
  UpdateDiscoveryStatus,
  ListDiscoveriesQuery,
  StarIntent,
  Star,
  CreateStar,
  UpdateStarIntent,
  ListStarsQuery,
  KnowledgeResponse,
  KnowledgeListResponse,
  RecordVisit,
  GetVisitQuery,
  VisitResponse,
  CaptureSourceType,
  ExtractionType,
  CaptureExtraction,
  FewShotExample,
  CorrectionStats,
  ReassignCapture,
  GroundingSpan,
  DeviceClassification,
  InsightType,
  Insight,
  SolutionProblemType,
  SolutionSeverity,
  SolutionStatus,
  SolutionReferenceType,
  Solution,
  CreateSolution,
  UpdateSolutionStatus,
  UpdateSolutionMetadata,
  ListSolutionsQuery,
  SolutionReference,
  CompoundScore,
} from "./types/index.js";
