/**
 * Claude CLI wrapper service (stub)
 *
 * Handles agent selection based on trust level and
 * execution of agent tasks via Claude CLI
 */

import {
  TrustContext,
  AgentProfile,
  AgentProfileId,
  ChatRequest,
  AGENT_PROFILE_DEFINITIONS,
  meetsTrustLevel,
} from '@mission-control/shared';

/**
 * Agent execution result
 */
export interface AgentExecutionResult {
  /** Agent response content */
  content: string;
  /** Token usage statistics */
  usage?: {
    inputTokens: number;
    outputTokens: number;
  };
  /** Whether the execution was successful */
  success: boolean;
  /** Error message if failed */
  error?: string;
}

/**
 * Select the appropriate agent profile based on trust level
 *
 * Rules:
 * 1. If a specific profile is requested, verify trust level allows it
 * 2. If requested profile not allowed, downgrade to highest allowed
 * 3. If no profile requested, use highest allowed for trust level
 *
 * @param trustContext - The trust context from request classification
 * @param requestedProfile - Optional requested agent profile
 * @returns The selected agent profile
 */
export function selectAgent(
  trustContext: TrustContext,
  requestedProfile?: AgentProfileId
): AgentProfile {
  // If a specific profile is requested, check if trust level allows it
  if (requestedProfile) {
    const profile = AGENT_PROFILE_DEFINITIONS[requestedProfile];
    if (profile && meetsTrustLevel(trustContext.level, profile.minTrustLevel)) {
      return profile;
    }
    // Requested profile not allowed - fall through to find best alternative
  }

  // Find the highest capability profile allowed for this trust level
  const profiles = Object.values(AGENT_PROFILE_DEFINITIONS);

  // Sort by capability (more tools = higher capability)
  const sortedProfiles = profiles
    .filter((p) => meetsTrustLevel(trustContext.level, p.minTrustLevel))
    .sort((a, b) => b.allowedTools.length - a.allowedTools.length);

  // Return highest capability allowed, or fallback to chat-readonly
  return sortedProfiles[0] || AGENT_PROFILE_DEFINITIONS['chat-readonly'];
}

/**
 * Execute an agent with the given request (stub)
 *
 * In production, this would:
 * 1. Build the system prompt with profile constraints
 * 2. Invoke Claude CLI with appropriate tool restrictions
 * 3. Stream/collect the response
 * 4. Validate output before returning
 *
 * @param agent - The agent profile to use
 * @param request - The chat request
 * @param trustContext - The trust context
 * @returns The agent execution result
 */
export async function executeAgent(
  agent: AgentProfile,
  request: ChatRequest,
  trustContext: TrustContext
): Promise<AgentExecutionResult> {
  // TODO: Implement actual Claude CLI integration
  // This is a stub that returns mock responses

  // Simulate some processing time
  await new Promise((resolve) => setTimeout(resolve, 100));

  // Build context-aware mock response
  const contextInfo = buildContextInfo(agent, trustContext);

  return {
    content: buildMockResponse(request.message, agent, contextInfo),
    usage: {
      inputTokens: Math.ceil(request.message.length / 4),
      outputTokens: 150,
    },
    success: true,
  };
}

/**
 * Build context information for mock response
 */
function buildContextInfo(
  agent: AgentProfile,
  trustContext: TrustContext
): string {
  const parts: string[] = [
    `Agent: ${agent.name}`,
    `Trust Level: ${trustContext.level}`,
  ];

  if (agent.allowedTools.length > 0) {
    parts.push(`Available Tools: ${agent.allowedTools.join(', ')}`);
  } else {
    parts.push('Available Tools: None (read-only mode)');
  }

  if (trustContext.userId) {
    parts.push(`User: ${trustContext.userId}`);
  }

  return parts.join('\n');
}

/**
 * Build a mock response for development/testing
 */
function buildMockResponse(
  userMessage: string,
  agent: AgentProfile,
  contextInfo: string
): string {
  return `[STUB RESPONSE - Claude CLI not yet integrated]

Your message: "${userMessage.slice(0, 100)}${userMessage.length > 100 ? '...' : ''}"

Context:
${contextInfo}

This is a placeholder response. In production, this would be generated by Claude via the CLI with the following constraints:
- Max tokens: ${agent.maxTokens || 4096}
- Allowed tools: ${agent.allowedTools.length > 0 ? agent.allowedTools.join(', ') : 'none'}
- Profile: ${agent.description}`;
}

/**
 * Get the Claude CLI command arguments for an agent profile
 * (For future implementation)
 */
export function getClaudeCliArgs(
  agent: AgentProfile
): Record<string, string | number | boolean | string[]> {
  const args: Record<string, string | number | boolean | string[]> = {
    '--max-tokens': agent.maxTokens || 4096,
  };

  // Add tool restrictions
  if (agent.allowedTools.length === 0) {
    args['--no-tools'] = true;
  } else {
    args['--allowed-tools'] = [...agent.allowedTools];
  }

  // Add system prompt additions if specified
  if (agent.systemPromptAdditions) {
    args['--system-prompt-suffix'] = agent.systemPromptAdditions;
  }

  return args;
}
